void leVet(float *a, int tam);
void printaVet(float a[], int tam);
void somaVet(float a[], float b[], int tam, float *vetSoma);
void subVet(float a[], float b[], int tam, float *vetSub);
void prodVet(float a[], float b[], int tam, float *vetProd);
void quadradoVet(float a[], int tam, float *vetQuadrado);
void absVet(float a[], int tam, float *vetAbs);
void expVet(float a[], int tam, float e, float *vetElevado);
float maiorVet(float a[], int tam);
void copiaVet(float dest[], int tam, float source[]);
void boaSort(float a[], int tam, float *ordenado);
void somaElementosVet(float a[], int tam, float *somaElementos);
